# Generated by Django 5.2.15 on 2026-08-07 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('server', 'Server'), ('workstation', 'Workstation'), ('other', 'Other')], default='other', max_length=20)),
                ('vlan_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('polling_interval_seconds', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)])),
                ('last_status', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('is_reachable', models.BooleanField()),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_checks', to='monitoring.device')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['device', '-checked_at'], name='monitoring__device__6f63b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.device')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='monitoring__device__a2bebd_idx')],
            },
        ),
    ]
