# Generated by Django 5.2.15 on 2026-08-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('admin_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('testing', 'Testing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('operational_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('testing', 'Testing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='monitoring.device')),
            ],
            options={
                'ordering': ['device', 'interface_index'],
                'constraints': [models.UniqueConstraint(fields=('device', 'interface_index'), name='unique_interface_index_per_device')],
            },
        ),
    ]
