# Generated by Django 5.2.15 on 2026-08-17 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_networkinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('text', 'Text'), ('boolean', 'Boolean')], max_length=20)),
                ('source_protocol', models.CharField(choices=[('snmp', 'SNMP'), ('system', 'System'), ('other', 'Other')], default='snmp', max_length=20)),
                ('oid', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('availability', 'Availability'), ('performance', 'Performance'), ('network_event', 'Network event')], default='availability', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='critical', max_length=20),
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(choices=[('syslog', 'Syslog'), ('snmp_trap', 'SNMP trap')], max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_events', to='monitoring.device')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='network_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.networkevent'),
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField()),
                ('collection_successful', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='monitoring.device')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='monitoring.networkinterface')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='monitoring.metricdefinition')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['device', 'metric_definition', '-collected_at'], name='monitoring__device__d644cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='networkevent',
            index=models.Index(fields=['source_ip', '-received_at'], name='monitoring__source__e9c5bb_idx'),
        ),
    ]
